---
title: "Abstract Linear Algebra"
output:
  html_document:
    css: "css.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Description^[The proper title for this course is Current Topics in Mathematics. This is a course that is designed by the instructor that can be anything related to mathematics but this time happens to be Abstract Linear Algebra with Applications to Differential Equations.]

I plan to spend approximately half of the semester exploring topics from "abstract" linear algebra. Then the remainder of the semester will be devoted to using algebraic methods to solve differential equations and systems of differential equations. 

Although I will assume familiarity with introductory linear algebra, I will not assume any background from differential equations. Some topics may intersect with group or ring theory (modern algebra), but any background will be covered as needed. Possible topics (in more or less detail according to interest):

Linear Algebra: vector spaces over different fields, infinite dimensional spaces, dual spaces, quotient spaces, Jordan canonical form, the matrix exponential, tensor products, and exterior algebras.

Differential Equations: solving DEs by factoring linear operators, the methods of undetermined coefficients, variation of parameters, and a partial fraction decomposition, technique for solving non-homogeneous linear DEs, using the matrix exponential and variation of parameters for solving systems of DEs, symmetry methods for solving DEs (finding integrating factors and very basic, very applied Lie theory), and (if there is interest), some differential algebra which would including a touch of differential and Galois theory which attempts to answer the question, "When can we solve a differential equation?"

## Linear Algebra Handouts

Some of the handouts are are directly related to the course while others are not. See Below for determining which handouts are directly revelant and not. 

[Linear Algebra Review Handout](https://billcookmath.com/courses/math5230-fall2016/math5230-RREF.pdf)

[Characterizing the Reals](https://billcookmath.com/courses/math4010-spring2018/math4010-spring2018-characterizing_reals.pdf)

[Axioms for the Reals](https://billcookmath.com/courses/math3220-spring2019/math3220-spring2019-real_axioms.pdf)^[Not directly relevant to this course]

[Computing Basis](https://billcookmath.com/courses/math5230-fall2016/math2240-fall2012-bases.pdf)

[Coordinate Matrix Example](https://billcookmath.com/courses/math5230-fall2016/math5230-fall2016-coordinate_matrix.pdf)

[Kernel, Range, & Composition Example](https://billcookmath.com/courses/math5230-fall2016/math5230-fall2016-Kernel_Range_Composition.pdf)

[Coordinate Matrix vs. Coordinates](https://billcookmath.com/courses/math5230-fall2016/math5230-fall2016-coordinate_transform.pdf)

[Dual Spaces](https://billcookmath.com/courses/math4010-spring2022/math4010-spring2022-dual.pdf)

[Jordan Form](https://billcookmath.com/courses/math4010-spring2022/math4010-spring2022-Jordan.pdf)

[Jordan and Function of Matrices Examples](https://billcookmath.com/courses/math4010-spring2022/math4010-spring2022-Jordan_examples.pdf)

[More Jordan and Function of Matrices Examples](https://billcookmath.com/courses/math3510-spring2013/math3510-exp_sqrt_examples.pdf)

[More Jordan Examples](https://billcookmath.com/courses/math3510-spring2013/math3510-spring2013-Jordan_form.pdf)






