---
title: "Applied Data Analytics Courses"
output:
  html_document:
    css: "css.css"
---

This page houses all the relevant courses I have taken over the years related to [Data Analytics](http://bulletin.appstate.edu/preview_program.php?catoid=31&poid=14051).

Summer (Session 1) 2024

* [CIS 5860 - Applied Analytics Project](Analytics_Project.html)

Fall 2023

* [CIS 5760 - Global Blockchain for Business](Blockchain.html)
* [ECO 5720 - Applied Econometrics](Econometrics.html)
* [ECO 5740 - Forecasting and Time Series Models](Time_Series.html)

Summer (Session 2) 2023

* [CIS 5450 - Project Management and Visualization](Project_Management.html)

Summer (Session 1) 2023

* [CIS 5845 - Unstructured Data Analytics](Unstructured.html)
* [MBA 5660 - Web Analytics, Data Privacy, and Security](Web_Analytics.html)

Spring 2023

* [CIS 5630 - Data Management](Data_Management.html)
* [CIS 5630 - Programming for Business Analytics](Programming_Analytics.html)
* [MAT 5340 - Introduction to Operations Research](Op_Research.html)
* [MBA 5200 - Problem Analysis and Quantative Methods](Analysis_Methods.html)
* [MBA 5820 - Executive Skills](Exec_Skills.html)

__________
