---
title: "Blog Posts"
output:
  html_document:
    css: "css.css"
    includes:
      after_body:
        - "footer.html"
        - "google_analytics.html"
---

__________

## Welcome to My Blog

Here, I share insights on analytics, data science, and technology. Check out my latest posts below!

### Recent Posts

[Welcome to My Analytics Blog!](intro_blog.html) - (2/22/25)

* A quick introduction to why I started this blog and what you can expect from future posts.

[My Journey: From Computer Science to Data Analytics and an MBA](why_analytics.html) - (2/28/25)

* A look into how I transitioned from computer science to mathematics, pursued analytics, and added an MBA to bridge the gap between data and business.

[Data Analyst vs. Business Analyst: What’s the Difference?](da_vs_ba.html) - (3/7/25)

* A dive into the differences between Data Analysts and Business Analysts, outlining their responsibilities, skills, and tools, and offering guidance on choosing the right career path.

[Eggcellent Analysis](Egg.html) - (3/14/25)

* An analysis of rising egg prices, this series takes readers on a data-driven journey through historical trends, economic drivers, predictive modeling, and seasonal patterns to uncover the factors behind this everyday cost.

[AI: The Good, the Bad, and the Ugly](AI.html) - (7/12/25)

* A look at how AI is accelerating innovation, reshaping jobs, and raising urgent questions about privacy, bias, and ethics, with reflections on where it’s headed next. 

[Power BI vs. Tableau: A Hands-On Dashboarding Comparison](Viz_Compare.html) - (7/22/25)

* A side-by-side comparison of Power BI and Tableau reveals key differences in dashboard design, sharing, filtering, and overall usability.

[Why This Site](Why_Site.html) - (8/23/25)

* A look at why I built this site to showcase my projects, track my growth, and share my learning in a dynamic, interactive way.

[Finding Growth Through Data: My Ripple Fiber Power BI Project](Ripple_Fiber.html) - (9/16/25)

* A deep dive into building a Power BI dashboard to analyze Ripple Fiber’s broadband coverage, benchmark competitors, and uncover key growth opportunities.

[Aptly Charlotte: By the Bedroom, By the Numbers - Part 1](Apt_Desc_Stats.html) - (10/10/25)

* An analysis of Charlotte’s rental market, examining descriptive statistics, rent variability, PPSF trends, amenity patterns, unit size dynamics, outlier behavior, and price correlations.

__________
