---
title: "Courses"
output:
  html_document:
    css: "css.css"
---

This page houses all the relevant courses I have taken over the years.

Courses I am Currently enrolled in:

Spring 2024

* [MBA 5110 - Economics for Decision-Making](Economics.html)
* [MBA 5220 - Operations and Supply Chain Management](Supply_Chain.html)
* [MBA 5600 - Managerial Finance](Finance.html)
* [MBA 5750 - Strategic Management](Management.html)

Previous Courses:

Fall 2023

* [CIS 5760 - Global Blockchain for Business](Blockchain.html)
* [ECO 5720 - Applied Econometrics](Econometrics.html)
* [ECO 5740 - Forecasting and Time Series Models](Time_Series.html)
* [MBA 5420 - Marketing Strategy and Applications](Marketing.html)

Summer (Session 2) 2023

* [CIS 5450 - Project Management and Visualization](Project_Management.html)
* [MBA 5320 - Managerial Accounting](Accounting.html)

Summer (Session 1) 2023

* [CIS 5845 - Unstructured Data Analytics](Unstructured.html)
* [MBA 5660 - Web Analytics, Data Privacy, and Security](Web_Analytics.html)

Spring 2023

* [CIS 5630 - Data Management](Data_Management.html)
* [CIS 5630 - Programming for Business Analytics](Programming_Analytics.html)
* [MAT 5340 - Introduction to Operations Research](Op_Research.html)
* [MBA 5200 - Problem Analysis and Quantative Methods](Analysis_Methods.html)
* [MBA 5820 - Executive Skills](Exec_Skills.html)

Fall 2022

* [CIS 3731 - Advanced Spreadsheet Analytics](Spreadsheet_Analytics.html)
* [ECO 3210 - Economics of Sports](Economics_Sports.html)
* [MAT 3310 - Discrete and Continuous Math Models](Math_Models.html)
* [STT 4890 - Introduction to Modeling and Analysis in Sports](Sports_Modeling.html)
* [STT 4900 - Internship](Internship.html)

Spring 2022

* [MAT 3110 - Introduction to Modern Algebra](Modern_Algebra.html)
* [MAT 4010 - Abstract Linear Algebra with Applications to Differential Equations](Abstract_Linear_Algebra.html)
* [STT 3860 - Statistical Modeling](Statistical_Modeling.html)

Fall 2021

* [MAT 2110 - Techniques of Proofs](Techniques_Proof.html)
* [MAT 2310 - Computational Mathematics](Comp_Math.html)
* [STT 3851 - Statistical Data Analysis II](Stat_Data_Analysis_II.html)
* [CS 3460 - Database](Database.html)

Summer (Session 2) 2021

* [MAT 2310 - Calculus with Analytical Geometry III](Calc_III.html)

Spring 2021

* [CS 2450 - Introduction to Computer Systems](Intro_Systems.html)
* [MAT 2440 - Introduction to Linear Algebra](Linear_Algebra.html)

Fall 2020

* [CS 2490 - Introduction to Theoretical Computer Science](Computer_Theory.html)
* [STT 3850 - Statistical Data Analysis I](Stat_Data_Analysis_I.html)

Spring 2020

* [CS 2440 - Computer Science II](CS_II.html)
* [MAT 1120 - Calculus with Analytical Geometry II](Calc_II.html)

Fall 2019

* [CS 1100 - Discrete Mathematics](Discrete.html)
* [CS 1440 - Computer Science I](CS_I.html)
* [MAT 1110 - Calculus with Analytical Geometry I](Calc_I.html)

__________
