---
title: "Data Management"
output:
  html_document:
    css: "css.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Description

This course prepares students to understand basic concepts of databases; normalization and denormalization of data in the context of analytics; structured query language (SQL) to extract, manipulate, and transform data for data mining enabled analytical solutions for business problems; use of cloud resources for data storage and access; and emerging trends in data management.

### Course Textbook

The course follows from *[Data Management: Databases and Analytics](https://www.richardtwatson.com/open/Reader/_book/data-management-databases-and-analytics.html)* Open Ed., by Dr. Richard T. Watson.

### Normalization

The following articles talk about data normalization.

[Normilization Microsoft](https://learn.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description)

[Normalization MariaDB](https://mariadb.com/kb/en/database-normalization-overview/)


### Other Stuff

The following Powershell and SQL files are examples of inserting a document into powershell, creating a T-SQL script for a cursor, and XML crib sheet for querying an XML document.

[Powershell Document Insert](Data_Management/insert-xmldocument.ps1)

[T-SQL Cursor Scaffolding](Data_Management/cursor-scaffolding.sql)

[XML Crib Sheet](Data_Management/xml-crib-sheet.sql)

### Emerging Tech Report

The following is an emerging tech report on blockchain.

[Emerging Tech Report](Data_Management/Emerging Technologies Report.pdf)

[Emerging Tech Presentation](Data_Management/Emerging Technologies Presentation.ppxt)

__________
