---
title: "Economics of Sports"
output:
  html_document:
    css: "css.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Description

Application of the techniques of microeconomic theory to the sports industry. These employ the tools of three core microeconomic fields - industrial organization, public finance, and labor economics - to the examination of professional and college sports. Topics studied include, but are not limited to, the prevalence of monopoly power in the sports industry, financing of stadiums and teams, growth of union power, salary determination, and the incidence of racial discrimination.


## Course Notes and Videos

The following are powerpoints and videos from the course.

### Chapter 1 and 2

[Sports Economics Introduction: Opportunity Cost](https://asulearn.appstate.edu/pluginfile.php/3275479/mod_resource/content/1/Sports%20Opportunity%20Cost.mp4)

[The Story of Babe Ruth and More...](https://asulearn.appstate.edu/pluginfile.php/3275480/mod_resource/content/1/Comparative%20adv.mp4)

[Sports Economics: The Basics of Demand](https://asulearn.appstate.edu/pluginfile.php/3275481/mod_resource/content/1/Demand%201.mp4)

[Sports Consumer Surplus](https://asulearn.appstate.edu/pluginfile.php/3275482/mod_resource/content/1/Sports%20Consumer%20Surplus.mp4)

[PowerPoint--Introduction](https://drive.google.com/file/d/1tkkMGS75dizk_tb-ZAQU8bCYX-iQe9uC/view?usp=sharing)

[Sports--Demand](https://drive.google.com/file/d/1ZuND9MOJieZzajCDfw1pY1EGZ4Leat37/view?usp=sharing)

[Consumer Surplus](https://drive.google.com/file/d/1Gm7D-c6zAaV7ciSLvCN2Epe8-uGIsp2S/view?usp=sharing)

### Chapter 2

[Elasticity of Demand](https://asulearn.appstate.edu/pluginfile.php/3275486/mod_resource/content/1/Elasticity%20of%20Demand.mp4)

[Elasticity Continued](https://asulearn.appstate.edu/pluginfile.php/3275487/mod_resource/content/1/Elasticity%202.mp4)

[Elasticity Application](https://asulearn.appstate.edu/pluginfile.php/3275488/mod_resource/content/1/Ed%20Application.mp4)

[Power Points Elasticity](https://drive.google.com/file/d/13lLmR2l5YLP-zbKu229nsGRJwMrxy_d_/view?usp=sharing)

### Chapter 3

[Sports League Intro](https://asulearn.appstate.edu/pluginfile.php/3275491/mod_resource/content/1/League%201.mp4)

[Sports Leagues Conclusion](https://asulearn.appstate.edu/pluginfile.php/3275492/mod_resource/content/1/League%202.mp4)

[Sports Team Profit Maximization](https://asulearn.appstate.edu/pluginfile.php/3275493/mod_resource/content/1/Firm%20Profits.mp4)

[Sports Teams Revenues](https://asulearn.appstate.edu/pluginfile.php/3275494/mod_resource/content/1/Revenues.mp4)

[Powerpoints Leagues](https://drive.google.com/file/d/1A8BZm7aBSJV4ZWlifafS8_pbOZr2WXf8/view?usp=sharing)

[Powerpoints Teams](https://drive.google.com/file/d/1A8BZm7aBSJV4ZWlifafS8_pbOZr2WXf8/view?usp=sharing)

### Chapter 4

[Broadcast Rights Part One](https://asulearn.appstate.edu/pluginfile.php/3275498/mod_resource/content/1/Broadcast%20Rights1.mp4)

[Broadcast Rights Part Two](https://asulearn.appstate.edu/pluginfile.php/3275499/mod_resource/content/1/Broadcast%20Rights2.mp4)

[Leagues and Monopoly Power](https://asulearn.appstate.edu/pluginfile.php/3275500/mod_resource/content/1/Monopoly1.mp4)

[Price Discrimination](https://asulearn.appstate.edu/pluginfile.php/3275501/mod_resource/content/1/Price%20Discrimination.mp4)

[Powerpoints Broadcast Rights](https://drive.google.com/file/d/1sTYVMjNjTdvdLnH2Gwh8YzgBeQ4PwqiO/view?usp=sharing)

[Powerpoints Monopoly Power](https://drive.google.com/file/d/1BrTrR0yME6LkVaGdPW1eZQ60P1GGLa7W/view?usp=sharing)

### Game Theory

[Introduction to Game Theory](https://asulearn.appstate.edu/pluginfile.php/3275530/mod_resource/content/1/Game%20Theory%201.mp4)

[The Prisoner's Dilemma](https://asulearn.appstate.edu/pluginfile.php/3275531/mod_resource/content/1/Prisoners%20dilemma.mp4)

[The Stag Hunt Game](https://asulearn.appstate.edu/pluginfile.php/3275532/mod_resource/content/1/Stag%20Hunt.mp4)

[Repeated Games](https://asulearn.appstate.edu/pluginfile.php/3275533/mod_resource/content/1/Repeated%20Games.mp4)

[Mixed Strategy Games](https://asulearn.appstate.edu/pluginfile.php/3275534/mod_resource/content/1/Mixed%20Strategy.mp4)

[Game Theory Power Points](https://drive.google.com/file/d/1U1AlZR-rngEdPn7CFbiGC-yZ06YeW9nZ/view?usp=sharing)

### Gambling

[Gambling 1 Introduction](https://asulearn.appstate.edu/pluginfile.php/3275515/mod_resource/content/1/Gambling%201.mp4)

[Insurance](https://asulearn.appstate.edu/pluginfile.php/3275516/mod_resource/content/1/Insurance.mp4)

[Gambling 2 Right Loving Behavior](https://asulearn.appstate.edu/pluginfile.php/3275517/mod_resource/content/1/Gambling%202.mp4)

[Gambling 3 Efficiency of Markets](https://asulearn.appstate.edu/pluginfile.php/3275518/mod_resource/content/1/Gambling%203.mp4)

[Gambling Powerpoints](https://drive.google.com/file/d/1PWE9XwhjI4K1JR9P9bClZpdLCLqd8sZg/view?usp=sharing)


### Stadium Funding

[Publiuc Funds for a Sports Stadium 1](https://drive.google.com/file/d/1RwqFOR2PsfbC3TozTMasYdzVWL5zZRzx/view?usp=sharing)

[Public Funds for a Sports Stadium 2](https://drive.google.com/file/d/1mUxh0X_0T0Gnr_MB2UqGiczW4VdxxtQb/view?usp=sharing)

[Economic Impact of a Sports Stadium](https://drive.google.com/file/d/1jGu9cM7NeUVaFhA3lE0EAj7IF27fQjnU/view?usp=sharing)

[Economic Value of a Sports Stadium Hedonic Price](https://drive.google.com/file/d/12cLOfW8sktc5zuNEO9lGup-922li6yap/view?usp=sharing)

[Economic Value of a Sports Stadium Contingent Valuation](https://drive.google.com/file/d/1NcimK_0M5LxPTKIEy_3iJ3Ojuo7njVje/view?usp=sharing)

[Public Funds Powerpoint](https://docs.google.com/presentation/d/1dR2_DaXKsZjoVRCyMsGShSVSqhuy_mWH/edit?usp=sharing&ouid=101085786338866865565&rtpof=true&sd=true)

### Labor Markets in Sports

[Labor Supply](https://drive.google.com/file/d/1pzShSD5M2mpVHWNdSMMiIRwRM0oZvxtX/view?usp=sharing)

[Labor Demand](https://drive.google.com/file/d/1f08VhuY4RuSajlE4HZq8tYbFRYZi1zI2/view?usp=sharing)

[Human Capital](https://drive.google.com/file/d/19S16OQwN7WB0ys7UtCktKs4sOpggwR-R/view?usp=sharing)

[Tournament Theory](https://drive.google.com/file/d/1Ro0Hkt4PudGJvJ67IwiM3GWsAlzW5_Q8/view?usp=sharing)

[Income Inequality](https://drive.google.com/file/d/1UdhIDfAIYDdrFc4wx_1r10kDUeN-s__0/view?usp=sharing)

[Labor Markets Power Points](https://docs.google.com/presentation/d/1hAlUD06gVfjjOJwsEP8n5DxKt_B4mV0E/edit?usp=sharing&ouid=101085786338866865565&rtpof=true&sd=true)

### Monopsony and Unions in Sports

[League Monopsony Power](https://drive.google.com/file/d/1_CXVrMmUzsOGi50j1rj8xByxNOcJXHyJ/view?usp=sharing)

[Free Agency](https://drive.google.com/file/d/1B7bfO9dwzW9XLrAVtKy9hHxh1NO9WGde/view?usp=sharing)

[Player Unions](https://drive.google.com/file/d/1VucMVfwlea-5zqCgxDfDwTL3cyjXZZVu/view?usp=sharing)

[Bilateral Monopoly](https://drive.google.com/file/d/1MtbyJsP1zsdmc6zHm3nf6MVnaNDJxm1y/view?usp=sharing)

[Labor Conflicts](https://drive.google.com/file/d/1deFZJ9eUeixy1_WYB9GK53MiL2jxYbm0/view?usp=sharing)

[Monopsony and Unions Power Points](https://docs.google.com/presentation/d/1-sjK2quGtDnKnpg0LzZeS5nOsZ3p_tKy/edit?usp=sharing&ouid=101085786338866865565&rtpof=true&sd=true)

### Discrmination in Sports

[Discrimination Theory](https://drive.google.com/file/d/1hlkFl7EE5UGdNN4s9wGhn7bPWhtICc95/view?usp=sharing)

[Employer Discrimination](https://drive.google.com/file/d/1HkT7gtYkTb5ObfZe4o4kfHa3jdORs0aZ/view?usp=sharing)

[Employee Discrimination](https://drive.google.com/file/d/1Ja_cEmfjhNgD5fanBddXI6oNa9RioSdp/view?usp=sharing)

[Consumer Discrimination](https://drive.google.com/file/d/1AVWi5fwAcLYwh7gpYcb4Q0wKSimDQbF4/view?usp=sharing)

[Measuring Discrimination](https://drive.google.com/file/d/1hUvwdY8_uBlUT66reYmp8PTBI9gE8eRW/view?usp=sharing)

[Gender Discrimination](https://drive.google.com/file/d/1KwkDWjPb0DHw8cFpOqjNjTQ51YxgwNQK/view?usp=sharing)

[Discrimination Power Points](https://docs.google.com/presentation/d/1lD4X5GTnmhzUWVLUlsjsAC6HpitJPvQ7/edit?usp=sharing&ouid=101085786338866865565&rtpof=true&sd=true)

### Supplements

[Supply and Demand Super Bowl](https://drive.google.com/file/d/1UfYo-KD89WUHcI7-BD0DlgguXlJ5broi/view?usp=share_link)

[Super Bowl ad Costs Soar but so does Buzz](https://drive.google.com/file/d/1rkfngCZypfl_aWnqGwZ3xAoEfGEdiQHT/view?usp=sharing)

[Rise and Fall of the Enforcer](https://drive.google.com/file/d/1D9wzT239cKfVHc55U1lS5wQRpx03HKH_/view?usp=sharing)

[Inside the Sports-Industrial Complex](https://freakonomics.com/podcast/sports-5/)

[Freakonomics Sports Washing](https://freakonomics.com/podcast/what-is-sportswashing-and-does-it-work/)

[Tit for Tat Strategy in NASCAR Bump and Run](https://www.youtube.com/watch?v=uzIObmp53zY)

[The Stag Hunt Game in NASCAR](https://firstmonday.org/ojs/index.php/fm/article/download/727/636/3855)

[Sports Gambling](https://freakonomics.com/podcast/sports-gambling/)

[Stadiums: Last Week Tonight with John Oliver (HBO)](https://www.youtube.com/watch?v=xcwJt4bcnXs)

[Not Just Another Labor Force](https://freakonomics.com/podcast/sports-6/)

[Here's Why your Not an Elite Athlete](https://freakonomics.com/podcast/elite-athlete/)

[ROSES XLIX Peter Groothuis "The Anti Flutie Effect: The Impact of Athletic Malfeasance"](https://www.youtube.com/watch?v=wfqSZAb7C2I)

[ROSES XXXIII John Whitehead "Beyond ghost games"](https://www.youtube.com/watch?v=zND-c6LMSV4)

[ROSES CXIV Pete Groothuis, "Positional Segregation and Career Length in Major League Baseball"](https://www.youtube.com/watch?v=mJDtM1QFiYo)

__________