---
title: "Internship"
output:
  html_document:
    css: "css.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Description

This was an analytics internship for the Sports Analytics Certificate using NCAA baseball data from 2019-2022 seasons. The coaches of the Appalachian State University baseball team wanted a 2-d distribution map of where flyballs were. Then I needed to grab the outfield balls. We don’t want the shallow fly balls. Once the correct hit balls were found, then it was a matter of creating a 2- D distribution map of where they happened. Lastly, I need to separate the handedness of the pitcher and batter more formally known as the platoon split.


## Code for Project

[Code for Project](Outfield_Alex2.html)

## Math

The following links are the math used to determine how far a player needs to walk to reach the optimal spot based on the pitcher. Each player will start from second base and move a certain distance then turn and continue another distance until the spot is reached.

[Right Field](https://www.desmos.com/calculator/q5ja8mxchd)

[Left Field](https://www.desmos.com/calculator/4muz2nmvnm)

[Center Field](https://www.desmos.com/calculator/cjjlsncywu)

__________