---
title: "Courses"
output:
  html_document:
    css: "css.css"
---

This page houses all the relevant courses I have taken over the years related to my major of [Math](http://bulletin.appstate.edu/preview_program.php?catoid=26&poid=11116&returnto=1505), minor in [Statistics](http://bulletin.appstate.edu/preview_program.php?catoid=26&poid=11114&returnto=1505), and [Sports Analytics Certificate](http://bulletin.appstate.edu/preview_program.php?catoid=26&poid=11278&returnto=1505).

Courses I am Currently enrolled in:
Fall 2022

* [MAT 3310 - Discrete and Continuous Math Models](Math_Models.html)
* [STT 4890 - Introduction to Modeling and Analysis in Sports](Sports_Modeling.html)
* [STT 4900 - Internship](Internship.html)

Spring 2022

* [MAT 3110 - Introduction to Modern Algebra](Modern_Algebra.html)
* [MAT 4010 - Abstract Linear Algebra with Applications to Differential Equations](Abstract_Linear_Algebra.html)
* [STT 3860 - Statistical Modeling](Statistical_Modeling.html)

Fall 2021

* [MAT 2110 - Techniques of Proofs](Techniques_Proof.html)
* [MAT 2310 - Computational Mathematics](Comp_Math.html)
* [STT 3851 - Statistical Data Analysis II](Stat_Data_Analysis_II.html)

Summer (Session 2) 2021

* [MAT 2310 - Calculus with Analytical Geometry III](Calc_III.html)

Spring 2021

* [MAT 2440 - Introduction to Linear Algebra](Linear_Algebra.html)

Fall 2020

* [STT 3850 - Statistical Data Analysis I](Stat_Data_Analysis_I.html)

Spring 2020

* [MAT 1120 - Calculus with Analytical Geometry II](Calc_II.html)

Fall 2019

* [MAT 1110 - Calculus with Analytical Geometry I](Calc_I.html)

__________
