---
title: "Advanced Spreadsheet Analytics"
output:
  html_document:
    css: "css.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Description

The course will help students develop in-depth analytics skills using spreadsheets to effectively analyze and solve real-world business problems and work with various forms of data. The teaching methods will include classroom laboratory based tutorials and case study scenarios involving problems common in real-life business practice, and critical thinking exercises designed to enhance their ability to formulate questions, select and analyze data, recommend solutions, and make significant business decisions.

## Case Projects

The following documents are case projects that use Microsoft Excel.

### College Town Budget

[College Town Budget Excel](Spreadsheet_Analytics/Budget/CollegeTownBudgetSolution_Pettis_Alex.xlsx)

[College Town Budget Report](Spreadsheet_Analytics/Budget/CollegeTownBudgetReport_Pettis_Alex.pdf)

### College Town Budgte Simulation

[College Town Budget Simulation Excel](Spreadsheet_Analytics/Simulation/Town_Budget_Simulation_Pettis_Alex.xlsx)

[College Town Budget Simulation Report](Spreadsheet_Analytics/Simulation/CollegeTownBudgetReport2_Pettis_Alex.pdf)

### East Coast Trucking

[East Coast Trucking Excel](Spreadsheet_Analytics/East_Coast/EastCoastTrucking_Pettis_Alex.xlsx)

[East Coast Trucking Report](Spreadsheet_Analytics/East_Coast/EastCoastTruckingReport_Pettis_Alex.pdf)

### Williams Investments

[Williams Investments Excel](Spreadsheet_Analytics/Williams/WilliamsInvestments_Pettis_Alex.xlsx)

[Williams Investments Report](Spreadsheet_Analytics/Williams/WilliamsClientReport_Pettis_Alex.pdf)

### Donaion Letter

[Donation Letter Access](Spreadsheet_Analytics/Donation/DonationLetter_Pettis_Alex.accdb)

[Donation Letter Excel](Spreadsheet_Analytics/Donation/DonationLetter_Pettis_Alex.xlsx)

[Donation Letter Report](Spreadsheet_Analytics/Donation/Donation_Letter_Report_Pettis_Alex.pdf)

### Appwich Data Analysis

[Appwich PowerBI](Spreadsheet_Analytics/Appwich/Appwich_Pettis_Alex.pbix)

[Appwich Report](Spreadsheet_Analytics/Appwich/Appwich_Report_Pettis_Alex.pdf)

__________